### ISSUE TITLE
Remove registrator from our deployment

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#1068]
We currently deploy [registrator](https://github.com/gliderlabs/registrator) which is used to dynamically identify running docker containers and register them at consul. I think we don't need to dynamically identify containers but rather register them explicitly once we deploy them via ansible. The [consul module](http://docs.ansible.com/ansible/consul_module.html) should make that pretty straightforward and it reduces our deployment by one service, which is not really used currently anyway.

Thoughts @ioana-blue? Did i miss a point of the registrator?

**Comment by ioana-blue** [comment]
Registrator is nice because it watches containers going down and up. What would happen in a dynamic environment where services come and go? (e.g., invokers leaving and new ones being spawned). It's up to you, my sense is that at one point when we deal with automatic scaling, we'll need something similar. I think this is early optimization.

**Comment by markusthoemmes** [comment]
I think we'll always know when we deploy what. It's not like containers are going to be around uncontrollably.

**Comment by markusthoemmes** [comment]
Done.
