### ISSUE TITLE
API v2:  add "gateway" entities

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#1268]
As discussed with @csantanapr,

In API v2 we plan to add support for "API Gateways" ... that is, a way to declaratively specify a mapping between a set of whisk assets (actions, triggers) and a REST API.

The general architecture would have two features:
     1)  a "gateway descriptor", an artifact which describes the mapping between the REST API and OpenWhisk stuff.   This will be based on OpenAPI/swagger.
     2) an "API Gateway" service, which implements the mapping.   This can be based on , say, nginx and OpenResty.

The OpenWhisk system will manage and persist entities which are "gateway descriptors" ... that is, extended swagger files.

For now, let's call these entities "gateways" ... we can debate and change the name if someone has a better idea.

We will add "gateway" entities to the set of entities managed by the OW API, which currently includes actions, triggers, rules, and packages.

This issue is intended to track the addition to the OW API to track gateway entities.

As an initial proposal, we would add CRUD REST as usual to the paths:
/openwhisk/namespaces/{ns}/gateways/{gatewayName}

So to be consistent with the rest of the API, we'd have the usual REST Verbs for GET and DELETE.    POST would be used to create or update a gateway entity, where the form body is the extended swagger object that is the gateway descriptor.   Let's not discuss PUT vs. POST REST philosophy in this issue, please ? :)

We intended to dogfood the implementation of the gateway management service ... we will introduce OW "system" actions which manage the persistence of these gateway entities, in a couchdb/cloudant database.

Work items include:
- [ ] Building the CRUD OW actions for gateway artifacts
- [ ](optional) introducing v2 of the OW API (technically not necessary since this is a non-breaking addition to the API)
- [ ] hook up routes in the controller to the CRUD actions
- [ ] ensure the gateway actions are only available to a privileged "system" user, not normal users.

**Comment by sjfink** [comment]
Step 2 of the API design:

Each gateway entity will include at least a collection of entities called routes.   A route will specify at least an HTTP Verb, an OW action, and some information about parameter mapping.

The API will support the usual CRUD OW operations on individual routes via:

/openwhisk/namespaces/{ns}/gateways/{gatewayName/routes/{id}

**Comment by mbehrendt** [comment]
thanks for the writeup @sjfink . 

a few thoughts / comments on this:
- naming: instead of gateway', what about calling it '(api-)mapping'? the rationale is...we're not allow crud operations of gateways or descriptors of gateways, but rather of these mappings?
- have we thought through what the master record of these mappings is going to be? eg if we allow creating them via the ow api -- where would we be storing them? e.g. if we store them in the ow db and in the gw itself, we might run into integrity problem given users can also interact with the gw without going through the ow api.
- cardinality / lifecycle dependency: what constitutes the boundaries of a mapping? eg if i execute `wsk action restify <actionname>`, i assume that is going to result in the creation of mapping for that action, right? how would i add more routes to a mapping (eg would i have to specify the mapping name (to your earlier point) as part of `wsk action restify`? can a mapping refer to multiple actions (i think the answer should probably be 'yes', given a mapping is imho an expression of an api) ?

**Comment by sjfink** [comment]
comment to track naming suggestions for the entity in our REST API which is a "collection of routes".  Please edit this comment to add more suggestions.

Options include:
*  gateway
*  mapping
*  route-collection
*  route-set
*  api-mapping
*  api-map
....

**Comment by sjfink** [comment]
> if we store them in the ow db and in the gw itself, we might run into integrity problems

Yes, there should be a single database which is the source of truth, and a single service which maintains the source of truth.   For now, the OW database will be the source of truth since there is no other option.

> cardinality

Let's restrict this issue to the API, not the CLI or UX.   From the API, I hope the API design above is clear that a "route collection ('gateway' entity)" contains a set of routes.

**Comment by mdeuser** [comment]
Is this the appropriate issue in which to discuss the RAS design for the backend route management actions?  Since these are effectively OpenWhisk components, integrating the action logging with the OpenWhisk system logging would be important (Kibana access).  Also, we may need to consider some sort of "workflow" id, which is another correlator that wraps 1 or more actions - to handle the case when route management actions invoke other actions.

**Comment by sjfink** [comment]
@mdeuser let's keep this issue focused on the API design, and move implementation stuff to separate issues.

**Comment by ddragosd** [comment]
Reading this thread got me wondering if the intent is to combine all concerns into a single database. From a microservice architecture perspective I think we could be dealing with distinct concerns that could be isolated in distinct microservices should we chose to. API Management may bring extra concerns on top of serverless ones, and I'm listing a few bellow:
* _restification_ - defining RESTful endpoints -> which I think is what this thread intends to solve, but feel free to keep me honest.
* _API Facade_ - a pattern for combining multiple endpoints into a single API . I think @mbehrendt might have referred to this when he asked _how would i add more routes to a mapping_
* _Traffic Management_ -Throttling and Rate limiting plans which are a combination of:
  * _API plans_ - rules around a single API
  * _Application plans_ - rules concerning applications that use an API
  * _User plans_ - rules concerning the end-users that use and application that consumes an API
* _Application AuthN and AuthZ_ - how do applications authenticate ? API-KEY, OAuth Tokens.
* _Users AuthZ_ - how to authorize users to consume an API. This is usually in a relation to a _User plan_. ( i.e.  applications may want to limit free subscribers more than the paid ones ) 

So if we implement all these into OW ( starting with _restification_ for now but possibly growing to the other aspects ) then would it make it easy to swap API Management implementations later ?

**Comment by rabbah** [comment]
webactions and API gw integration has landed long ago now.
