### ISSUE TITLE
docker version mismatch between travisCI 1.12 and dev environment 1.9.1

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk#1308]
currently [tools/travis/setup.sh](https://github.com/openwhisk/openwhisk/blob/master/tools/travis/setup.sh#L8) It's using 

```
sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -y install docker-engine=1.12.0-0~trusty

```

And the dev setup environments is using a different version
currently [tools/ubuntu-setup/docker.sh](https://github.com/openwhisk/openwhisk/blob/master/tools/ubuntu-setup/docker.sh#L17)

```
sudo apt-get install -y --force-yes docker-engine=1.9.1-0~trusty
```

This affects local environments for development ubuntu including Vagrant VM

currently [tools/macos/README.md](https://github.com/openwhisk/openwhisk/blob/master/tools/macos/README.md)
Instructions have 1.9.1

```
# install docker 1.9.1
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7702619bb7c1a42dc1ed83a57128727a1a1f5d9f/Formula/docker.rb
```

and boot2docker

```
docker-machine create -d virtualbox \
   --virtualbox-memory 4096 \
   --virtualbox-boot2docker-url=https://github.com/boot2docker/boot2docker/releases/download/v1.9.1/boot2docker.iso \
    whisk # the name of your docker machine
```

**Comment by csantanapr** [comment]
@domdom82 it's safe to upgrade to 1.12 for dev environment?

**Comment by domdom82** [comment]
there is two sides to this: in theory, you could update those three files in one step.
I did not do it yet because I wanted to walk up the pipeline first and update all servers before updating any clients. 

if you had provisioned a vagrant or docker machine and wanted to talk to any system of our pipeline, it would fail you would not be able to talk to those systems (e.g. registry).

it is safer to have a 1.9 client talk to a 1.12 server than have a 1.12 client talk to a 1.9 server.

but I do get the point of the mismatch on travis. we just started with travis because it is the start of our pipeline.

regarding the aufs vs. overlay yes that is a mismatch and it should all be overlay. also cors is no longer used. (never was actually)

**Comment by csantanapr** [comment]
@domdom82 thanks for the quick answer.

My two cents are that we should upgrade to 1.12 for the client, most people trying to use this repo are not using our internal system from their local dev setup.

**Comment by domdom82** [comment]
@csantanapr ran into the following problem today:

overlay fs needs at least kernel 3.19 to work. the vagrant box currently deploys 3.13.
we would have to be at 4.4 for docker 1.12 complete feature set so a kernel upgrade is necessary.

I don't know if it is possible to get a higher base version of that image. Otherwise we will have to patch the kernel and reboot the VM to load the kernel during startup which means we will no longer be able to do a simple "vagrant up" to deploy everything in one go.

until we solve that we could stay on aufs for the dev envs.

**Comment by csantanapr** [comment]
@domdom82 
- For native mac
  - Are there any problems using docker-machine and boot2docker?
- For ubuntu and vagrant 
  - We already use aufs [tools/ubuntu-setup/docker.sh](https://github.com/openwhisk/openwhisk/blob/master/tools/ubuntu-setup/docker.sh#L20)
  - On top we can detect the kernel version and if its 4.4 we use overlay if not then aufs during int he `docker.sh` script

**Comment by markusthoemmes** [comment]
Anything stopping us from just using the upcoming LTS `ubuntu/xenial64` in vagrant and be done with it? Comes with a 4.4 kernel and everything.
More future proof than building a couple of hacks into `docker.sh` imho.

**Comment by csantanapr** [comment]
nothing stopping us from using a different version of vagrant image as long it works.

The `docker.sh` is shared script used for both regular ubuntu users and vagrant.

Then it means we make Ubuntu Xenial 16.04 the minimum requirement 

How we solved this for Travis? Their default linux image already has the kernel we need to run dokcer 1.12 with overlay?

**Comment by markusthoemmes** [comment]
Overlay doesn't need 4.4, it needs 3.19. 4.4 is needed for full docker 1.12 security coverage (might not be able in travis aswell, so no showstopper there imho)

**Comment by csantanapr** [comment]
OK So 4.4 is really not required for local dev, then I would say let's start simple.

update docker.sh so it matches what we are currently using in travis
1. use overlay
2. install docker 1.12
3. update [tools/macos/README.md](https://github.com/openwhisk/openwhisk/blob/master/tools/macos/README.md) instructions for docker 1.12

**Comment by domdom82** [comment]
Travis refused to add xenial as a supported platform for the remainder of this year. See https://github.com/travis-ci/travis-ci/issues/5821

So I tend to agree with @csantanapr to keep both vagrant and travis in sync. There is one problem with overlay though, because vagrant is still no 3.13 which does not support overlay. So I suggest we stick with aufs for now as it is way easier then to bump the kernel during vagrant up.

On second note we will be having fun in the test cases that are about to use things like `--pids-limit` to protect from forkbombs. Features like these only work at 4.3 and above so we will have to skip them if the kernel does not support it. I have tested locally and Docker is fine with it. It will print a warning and go on without the feature.
