### ISSUE TITLE
Document How to Setup OpenWhisk Using Docker for Mac.

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#1431]
Currently, the documentation for setting up Docker on a Mac illustrates how to use OpenWhisk with Docker Machine. The documentation should be updated to demonstrate how to setup OpenWhisk on Docker for Mac.

**Comment by style95** [comment]
@dubeejw Is there anything in progress about this issue?
If not, I want to contribute on this issue.

It looks many things should be discussed such as "ansible environment in mac", "how to consider xhyve vm as local environment" and so on..

**Comment by dubeejw** [comment]
@style95, feel free to help out. I don't think any documentation has been created yet for this issue.

**Comment by style95** [comment]
While proceeding, I will describe the situation and workaround here.
Then it will be better for us to have same view and someone might give some advice or opinion.

**Comment by style95** [comment]
I faced two issues.

### 1. Ip address for local environment

In Docker for Mac environment, there is no docker network interface.
That means there is no 172.17.0.0/32 network.

This is because Docker for Mac takes advantage of xhyve VM.
In xhyve VM, there might be above network.
But in OS X side, there is no such network, it just do the port-forwarding to xhyve VM.

So current local setup inventory file does not work for "Docker for Mac".
I changed ip address of local inventory file as follow.

```
; db group is only used if db_provider is CouchDB
[db]
10.64.131.142 ansible_connection=local
```


### 2. Upper case in db name

While proceeding "wipe.yml" step, I noticed that if there any upper case in "ansible_user_id" or "ansible_hostanme", the step fails.

It can be easily resolved by changing them manually to lower case.
However, it will be better to make them to lower case during the ansible deployment steps because such case can be frequently occurred.

While I am doing this task, I manually changed my user name and host name to lower case.

**Comment by style95** [comment]
### Enabling Docker remote api
I faced an another issue:

```
TASK [invoker : determine docker root dir] *************************************
Friday 13 January 2017  11:50:22 +0900 (0:00:00.113)       0:03:50.436 ********
fatal: [10.64.131.142]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 61] Connection refused>", "redirected": false, "status": -1, "url": "http://10.64.131.142:4243/info"}
```

With "Docker for Mac", docker remote api is not available by default.
It is listed as known issue in docker.com.
https://docs.docker.com/docker-for-mac/troubleshoot/#/known-issues

Many users are wondering why this is missing.
https://forums.docker.com/t/remote-api-with-docker-for-mac-beta/15639/7

Anyway, the workaround is proxying the unix socket using socat command.
```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 4243:2375 bobrik/socat TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
```

**Comment by style95** [comment]
I am facing this issue.

```
+ /Users/Naver/git/openwhisk/ansible/../bin/wsk -i --apihost 192.168.0.23 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP --shared no /whisk.system/routemgmt -a description 'This package manages the gateway API configuration.' -a meta true -a get getApi -a post createRoute -a delete deleteApi -p host 192.168.0.23 -p port 5984 -p protocol http -p username admin -p password admin -p dbname style95_macbook13_gwapis -p gwUser '' -p gwPwd '' -p gwUrl http://192.168.0.23:9000/v1
error: Package update failed: The server is currently unavailable (because it is overloaded or down for maintenance). (code 5)
```

As per the ```roles/apigateway/tasks/deploy.yml``` file, it is looking for docker images "openwhisk/apigateway"

```
docker_container:
    name: apigateway
    image: openwhisk/apigateway
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    hostname: apigateway
```

But in my local environment, there is no images named "openwhisk/apigateway" as well as no running apigateway after deployment with openwhisk.yml

```
macbook13:ansible style95$ docker images | grep api
macbook13:ansible style95$
```

Is this normal? or did I miss anything?

I did ```./gradlew distDocker``` to build the openwhisk docker images

**Comment by rabbah** [comment]
@csantanapr @mdeuser can help with that.

**Comment by mdeuser** [comment]
The openwhisk/apigateway image should be pulled from Docker Hub during the explicity ansible deployment of the apigateway  `ansible-playbook -i environments/local apigateway.yml`

https://hub.docker.com/r/openwhisk/apigateway/

**Comment by style95** [comment]
I could successfully setup openwhisk with Docker for Mac.
I could install Catalog and run few nodeJS and Java actions.

I will recap above mentioned issues with suggestion.
Please give me feedback.

Based on that, I will create new PR.

**Comment by style95** [comment]
## Changes to be applied for "Docker for Mac"

### 1. ip address for local environment
In OSX environment, there is no docker network(172.17.0.0/32).

**Options**
1. In the document, guide user to change the ip address in ```ansible/environment/local/hosts```
2. Properly update the default IP
   (But I doubt there exists all-round default ip for mac and linux.)

### 2. Enabling Docker remote API
Docker remote API is not enabled by default in Docker for Mac.

**Options**
1. In the document, guide user to manually run socat container or do other workaround.
2. Create the ansible step for this issue.

I am inclined to make just guide for this issue.
There could be many workaround for this.
I think it will be better to give users a choice. 

### ETC

If there is no reason not to add apigateway.yml in the guide, I will include this step in all the guides.(including existing guides)

**Comment by style95** [comment]
One more question is, currently, ```wsklogs``` directory is created with root ownership.
Even though all files in each sub directory are create with current user ownership.

Is there any reason it should have root ownership?

**Comment by style95** [comment]
I could address the first issue with regard to ip address.

The workaround is as follow.

I added alias for loopback interface.
```
sudo ifconfig lo0 alias 172.17.0.1/24
```

And it magically works as expected : )


In details, basically 172.17.0.1(gateway) is osx host machine in container side.
So all the network traffic will be forwarded to host machine via 172.17.0.1 as a gateway.
And it will go out further to the internet via hosts` physical network interface.

The problem was host did not recognize 172.17.0.1 as its local network ip.
If container is trying to connect to other container via 172.17.0.1, host does not accept this request and all the containers are not reachable to each other.

So I added 172.17.0.1 as alias for loopback address and finally it works.

You can refer to this issue: https://github.com/docker/docker/issues/22753
