### ISSUE TITLE
make cli autodetect when it's outdated and allow auto-update

### ISSUE THREAD

**Issue by mbehrendt** [apache/incubator-openwhisk#1492]
the cli should check whether there is a new version available and offer to directly download it and update utself

**Comment by csantanapr** [comment]
Made this issue an ZunHub epic with children #1309 and #1677

**Comment by csantanapr** [comment]
We need to put in the information in content.json first to be able to query the latest version from the CLI.

**Comment by mdeuser** [comment]
I think there may be more than one issue here, so I'll add these for discussion

- Giving some sort of indication that a later CLI version is available.  If the CLI is changing relatively frequently, then receiving explicit notification of non-critical updates can get annoying; so I would prefer not explicitly prompting the user whenever there's an updated CLI.  Maybe a check-for-update command or some "later version is available" denotation in the `wsk property get` or the proposed `wsk --version` is sufficient for non-critical updates.
- Possibly have an CLI manifest with a high level description of what has changed since the previous version.  The user can decide if the update is worth getting.
- Provide a way to easily manually update the CLI.   I'm wary of making this automatic, but let's discuss.
- CLI/OpenWhisk compatibility check.  I expect that forthcoming OpenWhisk releases may not be backwards compatible with earlier CLI releases.  This incompatibility may vary from a total breakage to not being able to access/manage/configure a new OpenWhisk feature.  In the total breakage scenario, the CLI could block itself until the CLI is updated.

**Comment by dubeejw** [comment]
- We can have a property in the configuration file that enables/disables automatic checking for updates, and automatic updating of the CLI. 

- If there exist some sort of change log for Whisk, we can link to that. Otherwise, we can make a CLI change log using Git. `git log --after="2017-2-2" -- tools/cli`

- Definitely need manual updating support

- We can add custom messages to the build so that they are displayed to the user when the CLI checks for an update, or display those message when the CLI runs.

**Comment by mdeuser** [comment]
@dubeejw - re: the last bullet, I was thinking that the compatibility check is different than the CLI update check.  Both checks may occur at the same time or separately.  The compatibility check may be a mandatory check that could be performed by the CLI or OpenWhisk; although once the CLI is in it's own repo with it's own deployment cycle, this check is probably best performed by the CLI - assuming some sort of OpenWhisk/CLI compatibility table based on some sort of CLI and OpenWhisk versioning.

**Comment by csantanapr** [comment]
For some reason I can't move this issue using zenhub, maybe because it's an Epic.
I think for this home brew support will satisfy, as CLI distribution will not longer be a backend whisk API concern, clients are independently release.

Closing because I think if we implement homebrew support https://github.com/apache/incubator-openwhisk-cli/issues/153
will cover the ease of use of updating the wsk binary at least on mac.
