### ISSUE TITLE
API GW Actions : repackage common code into shared module(s)

### ISSUE THREAD

**Issue by mdeuser** [apache/incubator-openwhisk#1511]
The routemgmt packaged actions embed a few common routines that could be better packaged as single source module(s) and then required by the action code modules.

To package as NPM package with common dependencies, see http://jamesthom.as/blog/2016/11/28/npm-modules-in-openwhisk/

**Comment by rabbah** [comment]
List of refactoring and code improvements that should be applied to the `routemgmt` package:

1. [ ] refactor arg validation so that it validates all args at once and reports one error message (rather than sequential validation)
2. [ ] refactor common db operation into reusable module (this will remove nearly 1000 lines of clone and own code in favor of a more manageable module)
3. [ ]  remove unnecessary logging of arguments
4. [ ] remove all uses of `whisk.` and use promises instead since the `whisk` object is deprecated

**Comment by rabbah** [comment]
@mdeuser turn this to an epic? (related to #1690)

**Comment by mdeuser** [comment]
@rabbah - I believe PR #1730 addressed all items mentioned in this issue; and those not directly addressed were discussed with code being acceptable as-is.  OK to close this issue now?

**Comment by mdeuser** [comment]
Yep. ok to close.
