### ISSUE TITLE
Handle `Error`s in rejected `Promise`s

### ISSUE THREAD

**Issue by psuter** [apache/incubator-openwhisk#1643]
It's common in Node.js to reject a `Promise` with an instance of `Error`.

Doing this at the top-level in OpenWhisk results in arguably unexpected behavior:

```
$ cat errorPromise.js 
function main(args) {
    return Promise.reject(new Error("it broke"));
}
$ wsk action update errorPromise errorPromise.js 
ok: updated action errorPromise
$ wsk action invoke -br errorPromise.js 
{
    "error": {}
}
```

In contrast, the behavior when doing, e.g. `throw new Error("it broke");` is that the action container promotes it to an `error` object:

```
{
   "error": "An error has occurred: Error: it broke"
}
```

It would be consistent if rejected `Promise`s were promoted to a meaningful error (as well as potentially any other non-object argument to `reject`).

**Comment by psuter** [comment]
Any thoughts from frequent JS users @jthomas @csantanapr @jasonpet ?

**Comment by jthomas** [comment]
👍 on making them consistent. Putting rejected promises messages into `error` is the way to go IMO.

**Comment by mdeuser** [comment]
What should the behavior be when a promise is rejected with a json object as opposed to a string?

**Comment by psuter** [comment]
Currently, the container promotes any rejected value `V` to `{ error: V }`, since having an `error` field in an activation is the signal for, well, errors.

So `Promise.reject("oh no")` turns into `{ error: "oh no" }`, `Promise.reject({ reason: "panic" })` turns into `{ error: { reason: "panic" }}` etc.

There is the additional catch that if `V` is `undefined` (or in general false-y), it is replaced by `{}`. This is to address #1562, where the issue was that `{ error: undefined }` is the same as `{}`, which doesn't communicate that there was an error.

One proposal is that if `V` is somehow not JSON-serializable, we should fall back to what we do for exceptions, i.e. returning ```{ error: `An error has occured: $V` } ```. This would be consistent.

Now, an additional option is to treat instances of `Error` as special cases, and just do `{ error: V.message }` (additionally logging the stack trace), both for exceptions and rejected promises.

**Comment by ErikWittern** [comment]
I actually prefer the last option: turn `Promise.reject(new Error('oh no')` into `{ "error": "oh no" }` + logging of stack trace. The addition of `An error has occured: `, IMO, is unnecessary at best and confusing at worst.

**Comment by csantanapr** [comment]
I agree ☝️ with proposals bad Erik remark
Let's not add our own strings since this will be English only, I don't want to maintain nls or do a nls in the future :-)

Overwall proposal is ok, net undefined is confusing and getting the whole object or string developer sent via reject callback is a win

**Comment by skaegi** [comment]
I agree that the prefix "An error has occured:" is not at all desirable and should almost definitely be removed for NLS reasons among others but also because it limits the return type to a string. It could definitely be valuable to have a structure returned.

I would tend to not treat Promise.reject("oh no!") and Promise.reject(new Error("oh no!) identically and would suggest special casing Error Objects and converting them to a regular object with just a "name" and "message". Like so...

```
{
  "error": {
    "name":"Error",
    "message":"oh no!"
  }
}
```
It's tempting to also expose the enumerable properties of the Error but I would be cautious here. JavaScript Errors in my experience can contain references to Native elements as well as internal details you would not normally want to share and can also throw exceptions during a subsequent call to JSON.stringify. It can be done -- just prepare to write some pretty defensive code here.

Intead, If someone really really wants to pass stacks etc. I would suggest they create and reject with their own custom regular Object.

**Comment by rabbah** [comment]
current behavior:

```js
{
    "error": {
        "message": "it broke",
        "name": "Error",
        "stack": "Error: it broke\n    at NodeActionRunner.main [as userScriptMain] ..."
    }
}
```
