### ISSUE TITLE
Invoker is reporting health to load-balancer even if it's not able to process activations

### ISSUE THREAD

**Issue by jeremiaswerner** [apache/incubator-openwhisk#1711]
## Problem Statement
The invoker provides an endpoint that reports the health of the invoker. The load-balancer is calling the endpoints of each invoker. If an invoker is not healthy the load-balancer takes it out of consideration for further activation processing, i.e. is not dispatching any new activation on that invoker. If the invoker becomes healthy again, the load-balancer is adding it to the list of invokers for further activation processing.
Today the invoker health endpoint simply reports "healthiness" if the invoker process runs and the is able to handle the health endpoint.
The issue is that it also reports healthiness if it's not able to process activations, for example:
* if the kafka connection breaks,
* if the docker daemon is not responding in time

## Expected behaviour
The invoker health protocol should be enhanced that it reports "healthiness" if and only if it's able to process user activations and send active acks back to the controller/load-balancer. This can be done by enhancing the invokers health endpoint or by enhancing the load-balancer.

## Impact
If the invoker is unhealthy it still gets activations dispatched by the load-balancer. Activations are timing out or are stuck in the queue. The queue (number of in-flight actions) is rising and the users may run into throttles.

## Environment details:

* Bluemix (all)

**Comment by michaelmarth** [comment]
Comment from the peanut gallery:
How about making the load-balancer send test (dummy) payloads to each invoker that would get processed by the invoker by a specific system action that reports the ack *to* the load balancer. The advantage of such a setup would be that it is very close to measuring the _actual_ health of an invoker because if needs a healthy Kafka connection, healthy docker, etc.
Might require one "healthcheck" Kafka topic for each invoker so that this queue is always empty for the healthcheck (so that non-healthy invokers would not interfere with other parts of the system).

**Comment by markusthoemmes** [comment]
@michaelmarth that actually sounds like something we thought of as well:

We could use loadbalancer's existing data to enhance its health algorithm. We could examine the existing ACK messages for system errors and/or attach a timeout to an ACK of, say, 10 minutes (magic number, needs to be discussed) to also catch failing Kafka connections.

That way, the loadbalancer would know if an invoker is sick based on real live data and heuristics (i.e.: "Take an Invoker out if it has more than 5 invokes failed in 1 minute" or "Implement a exponential backoff for load dispatched to invoker X if requests fail").

What do you think?

**Comment by michaelmarth** [comment]
@markusthoemmes makes sense.

I think your idea has the advantage of not also catching catastrophically sick invokers, but additionally catching invokers with occasional problems where only some of the invocations fail. More importantly, it measures the actual invocations of app code - which is what matters.

The proposed 10 minutes seem very high. In my idea I had ~100ms in mind to catch failing invokers (basically the time it realistically takes for a test message to make it through an empty Kafka topic and start the healthcheck action). Maybe your proposal can be enhanced to catch catastrophic invoker failure faster? (as opposed to occasional failure which might take some time to be caught)

**Comment by ddragosd** [comment]
@michaelmarth 👍 to your suggestion.

One thought that comes to my mind is that if Kafka becomes slow for some reason and the invoker can't consume messages fast enough to invoke the `health-check` action within `100ms` will the LB bring the execution down b/c of that ? In this case the Invoker is fine, but its Kafka dependency is not.

What if we keep this idea but instead of marking an invoker unhealthy b/c it's slow in invoking actions, create a priority queue for invokers in the LB pushing the slow invokers to the bottom and invoke actions using the ones in the top ? we might end up with a _best effort QoS invocation logic_ in this way.

From the invoker's health status point of view one idea would be to make it dependent to the components the invoker manages:
* the machine it runs 
* the docker service running on that machine
* the containers it executed on that machine and how many resources they use
* etc

For cases when Kafka is not working as expected the question is if we wanna flag invokers as _unhealthy_ b/c of that. At that point we might be looking at scaling Kafka, adding more machines to run more invokers, reassigning partitions in Kafka and making it perform as expected. With the QoS based priority queue we could send new traffic to new invokers and wait for the slow ones to either recover or be taken out of service.

**Comment by rabbah** [comment]
Tagging related issue https://github.com/openwhisk/openwhisk/issues/1041.

**Comment by rabbah** [comment]
The health protocol now implements https://github.com/apache/incubator-openwhisk/issues/1711#issuecomment-273083757.
