### ISSUE TITLE
support go actions

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#19]
as per title

**Comment by jthomas** [comment]
I made a Go library to help with this.
http://jamesthom.as/blog/2016/06/21/serverless-go-actions/

**Comment by rabbah** [comment]
Here's another way to do it: https://www.ibm.com/blogs/bluemix/2017/01/docker-bluemix-openwhisk/

**Comment by rabbah** [comment]
We should more prominently document that openwhisk support Go actions (in addition to just about any precompiled binary).

**Comment by sciabarracom** [comment]
I am looking to the implementation of the nodejs runner. I wonder if the right implementation of a go action should not be instead of requiring an http server listening for the runCode post, and implement the unit code replacing the binary with the provided one. Or even create a .so library.

**Comment by csantanapr** [comment]
@sciabarracom 

What @rabbah shared that’s exactly what it does, it executed a binary the go code is just an executable. In this case you would get the input via a single string JSON from stdin 

This issue would be to take it to the level of in two fold
1. Instead of the user writing a go program to parse json from stdin or argv, it would be a more clean programming model to write a function that takes input as a structure object, there would be an epilogue to do the run of the user function parsing the the incoming JSON
2. The performance and memory reuse between invocations of different runs. Since the container might not even pause for invocations that are call back to back very fast or pause and resume would also preserve state on the container action

Sorry if I misunderstood your suggestion and comment

**Comment by sciabarra** [comment]
I wrote my proposal in the mailing list to make more clear what I mean.

**Comment by csantanapr** [comment]
Do you have a branch with changes or PR with some code maybe that would help understand better your proposal

**Comment by sciabarra** [comment]
Not yet, but I can work on it if it sounds acceptable.

**Comment by daisy-ycguo** [comment]
@csantanapr I wonder if we are able to close this issue, since we have [runtime-go](https://github.com/apache/incubator-openwhisk-runtime-go) repo.

**Comment by markusthoemmes** [comment]
Closing this as we have documented go actions and a dedicated repo.
