### ISSUE TITLE
Provide a performance test-harness

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk#2175]
It's been asked for multiple times and in parallel with the work on the new ContainerPool, comparable performance numbers are desperately needed.

As a first stake in the ground I propose the following approach:

1. Setup a  travis build, which deploys the OpenWhisk system
2. Run a sufficiently large number of invocations against that system. Load is to be defined. I propose for a starter: Blocking invocation of a noop action to get the throughput and latency numbers a user would expect.

That's pretty much what @ddragosd did for his docker-compose work here: https://github.com/openwhisk/openwhisk-devtools/blob/master/docker-compose/Makefile

The goal is to have a transparent and reproducible way to get to those numbers.

**Comment by sridhard** [comment]
@markusthoemmes what is the plan for this task? I am interested in knowing the openwhisk performance compared to aws-lambda/google-functions.

**Comment by markusthoemmes** [comment]
Copying my mail from the Apache dev-list for posterity:

Since many have asked I today started an effort to bring a comprehensive performance test suite for OpenWhisk out in the open.

Without much talking, here's the repository: https://github.com/markusthoemmes/openwhisk-performance

My initial idea was to have the tests run on Travis to get comparable numbers. Turns out, the Travis machines are way to weak (especially in terms of CPU cores) to host a whole OpenWhisk system and be able to perform extraordinary good.

The tests I did are based on the npm loadtest module, which is pretty much Apache Benchmark, with a few more features and nicer output. Currently there is only one test which surfaces end-to-end user latency of blocking invocations and maximum throughput. README.md has some more information on how exactly the tests are set up.

I do realize that those tests are the simplest you can get, but that's where I'd like to start. We can get more sophisticated tests any time.

To proceed from here, I'd like to have those tests run on beefier machines, to flesh out the real performance. Any ideas on how to do this in an open-source fashion, e.g. "out in the wild"?

**Comment by hsane2001** [comment]
Hi ,

Running this harness on a OpenWhisk deployment running on a native Ubuntu system runs into failures.
The noopLatency action is created and can be invoked via "wsk cli" but in the latency test "docker run" is used. Can you explain what is happening? It seems loadtest is being run in a docker container (outside the wsk system, since its not invoked by wsk) and then invokes the noop action "n" number of times. Is that whats happening? - Anyway I hit this error:

docker run --rm markusthoemmes/loadtest loadtest -n 10000 -k -m POST -H Authorization: basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1AK http://10.x.x.y:10001/api/v1/namespaces/_/actions/noopLatency?blocking=true
headers: object, {"host":"10.x.x.y:10001","user-agent":"loadtest/2.3.0","accept":"*/*","authorization":" basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1AK"}
[Fri Aug 04 2017 15:11:27 GMT+0000 (UTC)] INFO Requests: 0 (0%), requests per second: 0, mean latency: 0 ms
[Fri Aug 04 2017 15:11:32 GMT+0000 (UTC)] INFO Requests: 3895 (39%), requests per second: 779, mean latency: 1.3 ms
[Fri Aug 04 2017 15:11:32 GMT+0000 (UTC)] INFO Errors: 3836, accumulated errors: 3836, 98.5% of total requests
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Target URL:          http://10.x.x.y:10001/api/v1/namespaces/_/actions/noopLatency?blocking=true
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Max requests:        10000
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Concurrency level:   1
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Agent:               keepalive
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Completed requests:  10000
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Total errors:        9941
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Total time:          9.843250379999999 s
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Requests per second: 1016
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Mean latency:        1 ms
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO Percentage of the requests served within a certain time
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO   50%      1 ms
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO   90%      1 ms
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO   95%      1 ms
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO   99%      1 ms
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO  100%      388 ms (longest request)
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO  100%      388 ms (longest request)
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO
[Fri Aug 04 2017 15:11:37 GMT+0000 (UTC)] INFO   429:   9941 errors

**Comment by markusthoemmes** [comment]
@hsane2001 you need to "disable" the system limits if you want to run this test harness. Configure them in your environment using the `limits` key.

**Comment by hsane2001** [comment]
Thanks - that worked. Does each HTTP request from loadtest generate an action?

**Comment by markusthoemmes** [comment]
Done.
