### ISSUE TITLE
wsk action get --summary only works for actions with annotations

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#2270]
using `--summary` on an action without annotations gives the illusion that it's broken. (Same for a package. This option is also supported on a trigger and rule.)

```
> wsk action get /whisk.system/slack/post --summary 
action /whisk.system/slack/post: Post a message to Slack
   (parameters: text)

> wsk action create A -p a A
> wsk action get A --summary
action A
```

Perhaps it should give a warning the action has no annotations, or it should try to create a summary from the parameters attached.

The summary should perhaps invariably also include the kind, memory, timeout and logsize settings for an action.

For a rule, the summary includes the status for example even when an annotation is absent:
```
> wsk rule get R --summary
rule R
   (status: active)
```

**Comment by mdeuser** [comment]
@rabbah - just wanted to follow up on the 'try to create a summary from the parameters attached' suggestion.  maybe we create a union of the annotated parameters + default parameters.  what do you think about also including some designation of whether or not the the parameter is `final`-ized?

**Comment by rabbah** [comment]
i like it.

**Comment by underwoodb-sd-ibm** [comment]
@rabbah - with regard to @mdeuser 's suggestion for getting unions of annotated and default parameters: listing the union of these parameters can be kind of confusing all at once without at least differentiating the bound from the annotated parameters. For example:  
```
package /whisk.system/cloudant: Cloudant database service
   (parameters: bluemixServiceName, dbname, host, password, username, apihost, overwrite)
```
Which ones do I actually have access to? Which are/aren't important? I thought about something like:
```
package /whisk.system/cloudant: Cloudant database service
   (parameters: *bluemixServiceName, *dbname, *host, *password, *username, apihost, overwrite)
```
where parameters with * are bound, and if they were finalized they could have a different prefix. This could still be cumbersome, however, especially since we are at the mercy of users creating their own metadata parameters that may/may not even be useful. Thoughts?

**Comment by rabbah** [comment]
I like the * to indicate bound vs not bound. the point of the summary is to quickly show the user what the parameters are - only the catalogs have these and the common case is for users to just create parameters, not annotations.

in general the annotations are meant for documentation - they are currently not checked, so your point is right, it could get messy... but for the system/curated packages, i don't think it will be an issue since the goal is to document not obfuscate.

an alternative you alluded to it show the annotations separately from the parameters.

**Comment by mdeuser** [comment]
perhaps use:  * = bound, ** = bound, final
