### ISSUE TITLE
Argument list too long invoking action via docker container

### ISSUE THREAD

**Issue by tleyden** [apache/incubator-openwhisk#2465]
I'm running into an "argument list too long" error when trying to connect actions in a sequence, and the first action emits a very large JSON dictionary ([this](https://gist.github.com/tleyden/23bc31f3a2731ba4bc8a9da56568c8de) * 5)

## Environment details:

* Bluemix   

## Steps to reproduce the issue:

1. Create an OpenWhisk action github-user-aggregator that emits a JSON doc like [this one](https://gist.github.com/tleyden/23bc31f3a2731ba4bc8a9da56568c8de) -- however instead of 100 users, it has 500 users.
2. Create another OpenWhisk action (clobber-document) that runs in a docker container.  Here is the [dockerfile](https://gist.github.com/tleyden/7b665d3949ae80c2dc11e0677fe28d0c#file-gistfile1-txt) and here is the [code](https://gist.github.com/tleyden/7b665d3949ae80c2dc11e0677fe28d0c#file-clobber_doc-go).  I'm creating the action via `wsk action create clobber-document --docker myusername/clobber-document`  
3.  Connect the two actions in a sequence so that the clobber-document action receives the JSON doc emitted by the github-user-aggregator action, and tries to write it to the db

## Provide the actual results and outputs:

```
$ wsk activation logs 437465b647cf4d75995dd1367e307bc6
2017-07-08T23:26:15.031740914Z stdout: [Errno 7] Argument list too long
2017-07-08T23:26:15.032487263Z stdout: XXX_THE_END_OF_A_WHISK_ACTIVATION_XXX
2017-07-08T23:26:15.032503216Z stderr: XXX_THE_END_OF_A_WHISK_ACTIVATION_XXX
```

## Provide the expected results and outputs:

Expected it to write/update the db 

## Additional information you deem important:
* Happens every time   
* Is bash involved in passing the arguments around somewhere?  Where is the code where the python shim invokes the `/action/exec` executable in the docker container?  Is it just a matter of using `shell=false` in the python `subprocess` command?  (assuming that's being used)
* I think switching to the Custom Go Handler described in [James Thomas' blog post](http://jamesthom.as/blog/2016/06/21/serverless-go-actions/) might workaround the problem, since it would avoid shelling out.

**Comment by jthomas** [comment]
Hey @tleyden,

This looks like an internal kernel limit (MAX_ARG_STRLEN) on the maximum length of an argument.
https://stackoverflow.com/questions/29801975/why-is-the-subprocess-popen-argument-length-limit-smaller-than-what-the-os-repor

That file you referenced as the argument list is ~100KB, which means you're trying to pass 500KB.

I can think of a few ways around this.....

- Use an object store to write the data to. Pass the key as the output of the action, rather than the raw data. This is a common pattern to pass large amounts of data between actions once you get above a certain size. 

- Use the Apache Kafka integration as a message queue for invoking actions from these messages. Push the individual items onto the queue and then connect the receiving functions as a trigger feed source. They will be invoked on demand. 

- Use a fan-out and wait approach rather than a sequence. Have the action which produces this JSON manually split up and invoke the actions using the client SDK. The parent action will fire off the worker requests and then return once they have all returned. The disadvantage of this style is that you'll pay twice for the execution time, as the parent action will have to block waiting on the responses.

**Comment by tleyden** [comment]
Thanks @jthomas -- I'll close the ticket since it looks like an inherent limitation rather than an actual issue.

Wouldn't implementing the REST handler to receive the OpenWhisk invocation directly in Go also fix the issue?  Any other known issues with that approach?

I'm referring to the approach you mentioned in your blog post:

> Using the Docker SDK for OpenWhisk relies on a Node.js application to handle the platform HTTP requests, spawning a process to execute the user binary file.
> 
> Implementing the HTTP API, described above, in Go would allow us to remove the Node.js handler from the image. Compiling the Go Action source with the HTTP API handler into a single binary and using an Alpine Linux base image will dramatically reduce the image size.

**Comment by jthomas** [comment]
That's correct, you could just do that.
