### ISSUE TITLE
Missing "type": "object" in Swagger definition for KeyValue.value

### ISSUE THREAD

**Issue by cjolif** [apache/incubator-openwhisk#262]
https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/resources/whiskswagger.json#L1379

This is similar issue to #241

**Comment by cjolif** [comment]
Actually thinking more about it, it seems the value is not necessarily a JSON "object" but can be an integer or any JSON "value". So maybe adding "type": "object" is not the correct fix here.

**Comment by rabbah** [comment]
Indeed - a legal value for a parameter or annotation is any legal JSON value: object, array, number, string, boolean or null.

**Comment by cjolif** [comment]
A vendor specific value like `"x-type": "json"`might be added to let interpreters of the swagger to do that.

**Comment by daisy-ycguo** [comment]
[whiskswagger.json](https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/resources/whiskswagger.json#L1379) doesn't not exist. [apiv1swagger.json](https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/resources/apiv1swagger.json) doesn't have "type": "object" for KeyValue.value either. If adding "type":"object" is not the correct fix, do we want to fix it, or we just leave it as present and close this issue?

**Comment by rabbah** [comment]
The comment here suggested the fix https://github.com/apache/incubator-openwhisk/issues/262#issuecomment-218790277

**Comment by larandersson** [comment]
Tried to fix this by adding a new type definition and reference it from the KeyValue type, but then the tests failed, so I think it's best to leave this as it is. From my understanding, omitting the type is perfectly legal, because it means that it can be any type, which is exactly what we are trying to say (?). Using vendor extensions is probably not a good idea, because that will make our tests and code generators fail for sure. There is no silver bullet in OpenAPI v3 for this either, so I suggest we close this issue.
