### ISSUE TITLE
Indicate that process was killed due to OutOfMemory issue

### ISSUE THREAD

**Issue by tleyden** [apache/incubator-openwhisk#2652]
Currently if OpenWhisk kills a process due to exceeding memory limits, it doesn't appear to indicate that anywhere.  In my case I was seeing a result of 

```
"response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "The action did not produce a valid response and exited unexpectedly."
        }
    },
```

and it took quite a bit of digging to figure out that's why it was killed.  Would have been a big time-saver if there was another field in the result that somehow indicated that it was killed for this reason.

## Environment details:

* Bluemix

## Steps to reproduce the issue:

1.   Create actions + activations that have large amounts of output
2.   Modify [this monitoring code](https://github.com/tleyden/keynuker/blob/70b4d72476c205214caad66ad17c89cb323c622d/openwhisk_status.go#L84-L93) to set the `Limit` to 0 (unlimited).  This will cause it to pull hundreds of activations which include the full doc result of the activation, which may have hundreds of KB of output.  It all adds up to more than 256MB (or even 512MB) of RAM
3.  Install it to run on Bluemix using this [modified openwhisk-dockerskeleton](https://github.com/tleyden/openwhisk-dockerskeleton), which essentially runs a [python REST listener](https://github.com/tleyden/openwhisk-dockerskeleton/blob/master/actionproxy.py) that invokes a compiled Go executable and passes the JSON and receives the result over stdio.

## Provide the expected results and outputs:

```
"response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "The action did not produce a valid response and exited unexpectedly.",
            "detail": "Killed due to hitting 256MB RAM limit"   <-- this is the enhancement request!
        }
    },
```

## Provide the actual results and outputs:

```
"response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "The action did not produce a valid response and exited unexpectedly."
        }
    },
```

## Additional information you deem important:

* 100% reproducible each time
* I can submit a minimal reproducible test case if that will help
* I might be able to submit a PR if this is something folks want, and I was given a few hints about where in the codebase that this should be added

**Comment by markusthoemmes** [comment]
Submitting a PR would be awesomely awesome! Could you elaborate on the hints you got? 😁  Maybe I can provide a few more.

**Comment by rabbah** [comment]
@sven-lange-last maybe you want to post the information you found which would allow the invoker to report an error on killed that's more informative.

**Comment by rabbah** [comment]
Note that I would prefer if the "detail" is just the error.

**Comment by tleyden** [comment]
From a slack conversation around this issue, this seemed like a relevant place to discover that the container was killed due to memory limits:

https://stackoverflow.com/questions/38112968/how-to-know-the-reason-why-a-docker-container-exits/38113168#38113168

**Comment by rabbah** [comment]
Thanks. I was behind. This would be a very nice contribution.

**Comment by sven-lange-last** [comment]
@tleyden the SO link you provided above exactly describes how to determine whether a Docker container has been OOM killed.

The kernel message log should also contain hints about the OOM killer - but that's inefficient to parse.

If a Docker container gets OOM-killed due to memory limits, you will receive an error in one of the following lines: https://github.com/apache/incubator-openwhisk/blob/bb35e9cda94e246997fd8a4f81ecec396c2788cf/core/invoker/src/main/scala/whisk/core/containerpool/docker/HttpUtils.scala#L106-L117

We need to check which kind of error is thrown in this case and probably create a new specific error which is returned to the caller.

Once this error bubbles up in these lines,  we have to run `docker inspect` on the container and search for `"OOMKilled": true`.
https://github.com/apache/incubator-openwhisk/blob/bb35e9cda94e246997fd8a4f81ecec396c2788cf/core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala#L168-L181
