### ISSUE TITLE
C# / .NET Core

### ISSUE THREAD

**Issue by Daniel15** [apache/incubator-openwhisk#3003]
From the site:
> Currently, OpenWhisk supports NodeJS and Swift; more languages will be supported soon.

Are there any plan to support C#, via .NET Core?

**Comment by mrutkows** [comment]
Hi Daniel, until now I do not recall anyone in the community explicitly suggesting adding a C# or .NET library, but personally I have heard one or two people at recent conferences describe a personal desire to try supporting one or the other.  Since we are indeed community driven, all it would take would be a pull request for us to review and consider adding support for more runtime languages and have the community back it and affirm they would be willing to support it.  

In fact, we successfully added support for PHP (7.1) around August following this approach using the contributions of an individual developer and would welcome similar ones.  If you want to solicit interest from the community, it would be great to post to our Apache project "dev" list (dev@openwhisk.incubator.apache.org).

Here is a link to tell you how to subscribe to the list: http://openwhisk.incubator.apache.org/contact
If you want to contribute, our Wiki has a few instructions on "how to become a Contributor" here: https://cwiki.apache.org/confluence/display/OPENWHISK/OpenWhisk+Project+Wiki

and again, thanks for your interest.  Personally, I would love to see more supported language runtimes and loved my time using C# more than a few years ago!

**Comment by jonpspri** [comment]
Has there been any discussion around this since the last post?  I've got a potential user in the wings -- I may just grab the Go runtime prototype and see if I can wrestle C# into it instead.

**Comment by judavi** [comment]
Looks like .netCore is included now : https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-dotnet.md

**Comment by rabbah** [comment]
Indeed - Thanks to @shawnallen85.
