### ISSUE TITLE
Can I spawn action containers not only use docker?

### ISSUE THREAD

**Issue by YellyYU** [apache/incubator-openwhisk#4002]
Hey guys, I'm planning to use openwhisk for serverless sandbox boot time analysis. I see that openwhisk uses docker containers to bundle and manage user codes, so I suppose somewhere in the server side docker command (or api) like `docker run` is called. Now I'm wondering is it possible for me to spawn containers using other commands other than docker, such as `runc run` command, through several modifications to the source code? I'm a new comer to openwhisk project and not very familiar to the whole picture of openwhisk, so if you can tell me where the codes spawning action containers are, and what's the recommending way to achieve what I want, that would be very nice. Thanks in advance!

**Comment by markusthoemmes** [comment]
Hi @YellyYU,

yes this is definitly possible. In fact, the current implementation even mixes docker/runc commands for performance reasons.

In theory, you'll need just another implementation of the `Container` trait (see [`DockerContainer.scala`](https://github.com/apache/incubator-openwhisk/blob/master/core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala) for an example implementation). The [`RuncClient`](https://github.com/apache/incubator-openwhisk/blob/master/core/invoker/src/main/scala/whisk/core/containerpool/docker/RuncClient.scala) is not fully implemented as of today because we didn't need it, feel free to add whatever you need there.

I hope that helps!

**Comment by rabbah** [comment]
@YellyYU i hope the above answered your question - please reopen if needed.

**Comment by rabbah** [comment]
@sven-lange-last it would be useful to document the assumptions - where is a good place to do that?

**Comment by sven-lange-last** [comment]
@rabbah I opened #4255 to put the documentation directly in the code into the trait that needs to be implemented.
