### ISSUE TITLE
only 8 concurrent containers running at a time

### ISSUE THREAD

**Issue by Kingdo777** [apache/incubator-openwhisk#4526]
I deployment the Openwhisk locally in an EC2 VM Instance with docker Compose, in terms of the docs ["How to setup OpenWhisk with Docker Compose"](https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/README.md)
My VM has 4 vCPU / 8GB MEM

but I can only start 8 concurrent containers running at a time!!!
how can I increase it?

**Comment by dgrove-oss** [comment]
The default deployment configuration sets the invoker_user_memory (the amount of memory available to run user actions) to 2GB (https://github.com/apache/incubator-openwhisk/blob/master/ansible/group_vars/all#L192). The default memory for a node action is 256MB.  So that's where the limit of 8 concurrent containers you are seeing is coming from (2048/256 = 8).

If you change invoker_user_memory when you deploy your OpenWhisk instance, you can configure it to enable more concurrent actions.

**Comment by rabbah** [comment]
@Kingdo777 did you figure this out? Please reopen if you still need help.
