### ISSUE TITLE
Travis errors due to missing `controller:latest` image.

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk#4539]
I'm seeing failures in Travis this morning for Apache OpenWhisk repos due to the `controller:latest` image being referenced. I'm guessing this is due to the move to use `nightly` in accordance with ASF guidelines.

https://travis-ci.org/apache/incubator-openwhisk-client-js/builds/554135693
https://travis-ci.org/apache/incubator-openwhisk-cli/builds/554119370

```
fatal: [controller0]: FAILED! => {"changed": false, "msg": "Error pulling image openwhisk/controller:latest - 404 Client Error: Not Found (\"manifest for openwhisk/controller:latest not found\")"}
```

This comes from the following task: 
https://github.com/apache/incubator-openwhisk/blob/ef8b06f499764d38b29c1a8095fba09836d666a1/ansible/roles/controller/tasks/deploy.yml#L312-L331

The `docker.image.tag` uses `latest` I guess? Should that config value be changed to `nightly`?

**Comment by jiangpengcheng** [comment]
I think change the `default_image_tag` to `nightly` in `ansible/group_vars/all` should be better comparing to change travis configuration in other projects like [incubator-openwhisk-cli](https://github.com/apache/incubator-openwhisk-cli)

**Comment by jthomas** [comment]
This seems sensible to me but I'm not familiar enough with the configuration to make a judgement on whether this is the best approach. Will let someone more experienced decide.... 

cc @rabbah @dgrove-oss

**Comment by style95** [comment]
With #4538, we need to change this to `nightly` as well to make Jenkins build work because it uses a private registry.
https://github.com/apache/incubator-openwhisk/blob/f8a1506b2edc5e61476e44b924962a567c283b22/gradle/docker.gradle#L43

But this will change the behavior of local build and deployment via a private registry.
I think it is correct to use `latest` if a user uses images built in a local environment with a private registry(deployed via OpenWhisk).

And for build jobs such as CLI and client-js, I think it is correct to use `nightly` built official images.
Because it just requires them as a dependency and requires a "fresh" version from the master branch.

So I am inclined to change CI configuration of CLI and client-js instead replacing `default_image_tag`.

**Comment by dgrove-oss** [comment]
I think the right thing to do is to change downstream repos travis scripts to be specific that they are pulling nightly where appropriate.   Trying it for the cli here https://github.com/apache/incubator-openwhisk-cli/pull/450.

**Comment by dgrove-oss** [comment]
I believe this is all sorted out now.
