### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by pankaj-dahiya** [apache/incubator-openwhisk#4562]
ubuntu@ubuntu:~$ sudo docker pull openwhisk/controller
Using default tag: latest
Error response from daemon: manifest for openwhisk/controller:latest not found

**Comment by sven-lange-last** [comment]
You didn't specify a lot of information in this issue. I guess you pulled `openwhisk/controller` successfully in the past which resolves to `openwhisk/controller:latest`.

We recently changed `latest` to `nightly` because of Apache requirements. Unfortunately, `nightly` does not have the `docker pull` convenience - `openwhisk/controller` will never expand to `openwhisk/controller:latest`.

You will have to pull `openwhisk/controller:nightly` explicitly.

In the long term, Docker convenience images for the latest OpenWhisk release may be tagged `latest`.

Also look here: https://hub.docker.com/r/openwhisk/controller/tags

**Comment by dgrove-oss** [comment]
Closing as @sven-lange-last's explanation explains nicely.
