### ISSUE TITLE
reconsider persistence strategy for trigger activations

### ISSUE THREAD

**Issue by sjfink** [apache/incubator-openwhisk#512]
Currently we create an activation record in cloudant for each "trigger activation".

We've already seen large numbers triggers a day, and I expect we'll soon get up to even larger large numbers or more.

The number of actions and rule activations is much, much less.

I expect the current impl to choke relatively soon.   It's too much data to persist forever in cloudant.

I think perhaps we should not store trigger activations at all.   Instead, I'd suggest simply storing a count of each trigger fired per day, or maybe per hour.

**Comment by domdom82** [comment]
Do we lose any relevant information if we change to a count-per-day/hour strategy?
Off the top of my head I think as a user I would like to be able to backtrack the activations so I could determine if my rules work, i.e. 

```
t1 -> seq1 -> a1 -> a2 -> a3
```

On the other hand I don't even get that "in-order" list using `wsk activation poll` today due to the asynchronous nature of events. 

However it may seem odd that we track activations of other things such as actions exactly, but not triggers. 

What a about a hybrid model where we track all activations individually per day **and as a count** but have automation in place that flushes the "per day" part regularly?

As a user you usually only want to track down individual trigger / action activations as you are developing them. Once they work fine you are more interested in statistical values, i.e. "how many times did my action fire this week" etc. 

By flushing we could take some of the load off of the db.

**Comment by rabbah** [comment]
> On the other hand I don't even get that "in-order" list using wsk activation poll today due to the asynchronous nature of events.

You surely get trigger before rule before action. If you see otherwise then there's a defect.

**Comment by domdom82** [comment]
Well that might be true for simple cases in general. However if there are multiple rules in place and multiple triggers firing the activation poll can become confusing. Maybe a column "triggered by" helps..?

**Comment by rabbah** [comment]
The trigger activation has a `result` property that records the event details. This can be potentially large and compounded by the number of triggers will have a large footprint. As a short term action: remove the payload from the activation for triggers.

@sjfink @jthomas FYI.

**Comment by mbehrendt** [comment]
can we limit the size of each record getting logged instead of dropping the entire log entry irregardless of the size of what is being logged in a particular entry?

to @sjfink 's original issue description -- i think we should rather establish a policy of deleting old entries vs reducing the log details per entry.

**Comment by rabbah** [comment]
We're not talking about dropping logs. Triggers don't have logs. I some time ago allowed triggers to record their payload as their result in the activation record. One can do this logging explicitly by sequencing an action hence no information is lost.

Logs separately are subject to a system limit of 10MB currently.

**Comment by rabbah** [comment]
Status today: activations of triggers with no active rules attached are dropped.
