### ISSUE TITLE
Document CouchDB reduce_limit requirement

### ISSUE THREAD

**Issue by psuter** [apache/incubator-openwhisk#693]
Users using their own CouchDB should run the equivalent of this command, from `start-couchdb-box.sh`:

```
# Disable reduce limit on views
${CURL} -X PUT ${COUCHDB_PROT}://${COUCHDB_HOST}:${COUCHDB_PORT}/_config/query_server_config/reduce_limit -d '"false"' -u ${COUCHDB_USER}:${COUCHDB_PASS}
```

**Comment by rabbah** [comment]
This is covered by the ansible couch playbook: https://github.com/openwhisk/openwhisk/blob/master/ansible/roles/couchdb/tasks/deploy.yml#L31

Also there is a reference to this here: https://github.com/openwhisk/openwhisk/tree/master/tools/db#using-couchdb. Adding the above to make it more explicit in the `db` docs is good idea,

**Comment by tuler** [comment]
My bad I didn't see that in the docs. Sorry.

**Comment by willholley** [comment]
do you know why `reduce_limit` is needed? As a rule of thumb, that's an indication of a bad reduce function (reduce functions need to reduce) - Cloudant doesn't allow this to be disabled so it will become a problem there as well but probably requires a larger data volume before the warning is triggered.

**Comment by rabbah** [comment]
The views that are computed perform maps, not reductions - we precompute views that allow queries by date, namespace, and action name.

**Comment by lehoanganh** [comment]
@rabbah : we can refactor, however it was the original idea where shared stuff is placed in central, cloudant and couchdb use the things as dependency like every programmer will do (place common stuff in functions). Afterwards we decided to make each role like cloudant, couchdb to self-contained, so that one can use each role independently (don't have to import another roles). That's why for now, cloudant and couchdb have redundany

My suggestion is, take the couchdb as example and write the new one for the own couchdb

**Comment by willholley** [comment]
@rabbah in that case, disabling reduce_limit should not be required. Looking at the views in the repository, https://github.com/openwhisk/openwhisk/blob/d19d9de7df07cc4e69c2c47dc7c29a903ec6bba8/tools/db/loadTransientDBViews.sh#L60 appears to be the offending reduce function. I suggest that instead of using a reduce, this is pulled out as a separate map function (e.g. packages-public), or a compound key used.

**Comment by rabbah** [comment]
@willholley thanks - my thinking was to avoid recomputing the same map but your point is well taken.

**Comment by rabbah** [comment]
#3152 will update the docs to drop this step from the instructions (See https://github.com/apache/incubator-openwhisk/pull/3152/commits/859559b5461f07f302183d1224ed7549071d53f4).

**Comment by rabbah** [comment]
The offending view was long removed, and docs updated by https://github.com/apache/incubator-openwhisk/pull/3152.
