### ISSUE TITLE
`wsk trigger get` does not show any parameters

### ISSUE THREAD

**Issue by bjustin-ibm** [apache/incubator-openwhisk#929]
After a trigger is created, I cannot find any way to see the parameters used to create the trigger. This is important information required to understand what the trigger does and when it will fire.

When I run `wsk trigger get` there is a `parameters` field, but it always appears to be empty. This is where I would expect to see the parameters that were used to create the trigger.

**Comment by rabbah** [comment]
This is related to #471.

**Comment by rabbah** [comment]
Note that when you create a trigger with a feed, the parameters are passed to the feed and not stored on the trigger - because usually the parameters you are passing to the feed include credentials or other secrets that are only needed to negotiate with the event source. If those parameters are stored as parameters of the trigger, then they are available to the action that is invoked via a rule - this may not be desired.

What's proposed in 471 is that the feed may choose to store certain parameters on the trigger - and we may want to store these in a different field that parameters (since they are related to the life cycle management of the feed).

**Comment by mdeuser** [comment]
@bjustin-ibm - Did the comment above address this issue (i.e. can be closed)?

**Comment by bjustin-ibm** [comment]
@mdeuser #471 is still open and, once it is resolved, I suspect the CLI may need to react in order to show this new information. I would suggest using a "blocked" label, but it seems this repo doesn't have one already 😞

**Comment by dubeejw** [comment]
@bjustin-ibm, it this this is fixed now?

**Comment by mdeuser** [comment]
@bjustin-ibm - does the cli work for you now?
```
>wsk trigger get myt_w_param_ann
ok: got trigger myt_w_param_ann
{
    "namespace": "mdeuser_dev",
    "name": "myt_w_param_ann",
    "version": "0.0.1",
    "annotations": [
        {
            "key": "ann_key",
            "value": "ann_value"
        }
    ],
    "parameters": [
        {
            "key": "key",
            "value": "value"
        }
    ],
    "limits": {},
    "publish": false
}
```

**Comment by rabbah** [comment]
>  I suspect the CLI may need to react in order to show this new information. 

I don't think so in that one proposed solution is to update the trigger with the parameters (either as annotations or actual param values). In either case, the CLI will show these readily if the information exists as shown above.

**Comment by bjustin-ibm** [comment]
> @bjustin-ibm - does the cli work for you now?

@mdeuser The trigger I am creating is from a feed and, at this point, I don't even see an empty "parameters" field when I get the trigger. I understand the current limitation of not storing parameters for triggers created from feeds, but the point of this issue is to address this limitation to make it less limiting.

**Comment by rabbah** [comment]
I think that's captured in #471. (one of these is a duplicate of the other.)

**Comment by bjustin-ibm** [comment]
I'm ok closing this one then.
